# Generated by Django 5.0 on 2023-12-19 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('house_number', models.CharField(max_length=20, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'контактная информация',
                'verbose_name_plural': 'контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('model', models.CharField(max_length=100, verbose_name='модель')),
                ('release_date', models.DateField(verbose_name='дата выхода товара')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('node_type', models.IntegerField(choices=[('Factory', 'Factory'), ('Retail Network', 'Retail Network'), ('Individual Entrepreneur', 'Individual Entrepreneur')], verbose_name='тип узла')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='задолженность')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nodes.contact', verbose_name='контакты')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodes.networknode', verbose_name='поставщик')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nodes.product', verbose_name='товары')),
            ],
            options={
                'verbose_name': 'звено',
                'verbose_name_plural': 'звенья',
            },
        ),
    ]
