# Generated by Django 5.0 on 2023-12-19 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networknode',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='nodes.networknode', verbose_name='компания реализатор'),
            preserve_default=False,
        ),
    ]
