# Generated by Django 5.0 on 2023-12-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_remove_networknode_products_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='node_type',
            field=models.CharField(choices=[('Factory', 'Factory'), ('Retail Network', 'Retail Network'), ('Individual Entrepreneur', 'Individual Entrepreneur')], verbose_name='тип узла'),
        ),
    ]
